fix misc issues
GeoWerkstatt/qgis-custom-news-feed pull request #22
Opened 2023-06-30 06:44 UTC by olivergrimm

based on customer feedback:
-plugin start behaviour changed
-PublishingDate for pinned messages new optional
-fix bug in the case of no unread messages and pinned messages

2023-06-30 07:08 UTC, danjov requested changes

2023-06-30 07:08 UTC, danjov commented on custom_news_feed/custom_news_feed.py
> +        #QgsMessageLog.logMessage(u'Reading feed from: ' + news_json_file_path,'Custom News Feed')
REQ: Auskommentierten Code löschen

2023-06-30 07:08 UTC, danjov commented on custom_news_feed/custom_news_feed.py
> +                    #self.current_pinned_message = news["PinnedMessage"]
REQ: Auskommentierten Code löschen

2023-06-30 07:08 UTC, danjov commented on custom_news_feed/custom_news_feed.py
> +            if 'StartPublishingDate' in json.loads(json.dumps(news["PinnedMessage"])) and 'EndPublishingDate' in json.loads(json.dumps(news["PinnedMessage"])):
PP: `json.loads(json.dumps(news["PinnedMessage"])` in Variable auslagern. So wird das Ganze immer nur einmal aufgerufen.

2023-08-09 08:59 UTC, danjov requested changes

2023-08-09 08:59 UTC, danjov commented on custom_news_feed/custom_news_feed.py
> +            # self.dockwidget.show()
REQ: Auskommentierten Code löschen

2023-09-26 07:41 UTC, olivergrimm commented
@Philippluca Bitte um formales Review damit ich mergen kann

2023-09-27 09:23 UTC, Philippluca approved these changes

2023-09-27 09:23 UTC, Philippluca commented on README.md
>  #### Label for the input box to select configuration file (locally or via url)
Q: Muss die Doku für Pinned messages auch angepasst werden?

2023-09-29 13:43 UTC, merged